= Parameters

The parent key for all of the following parameters is `exoscale_cloud_controller_manager`.

== `namespace`

[horizontal]
type:: string
default:: `syn-exoscale-cloud-controller-manager`

The namespace in which to deploy this component.

== `manifests_version`

[horizontal]
type:: string
default:: https://github.com/projectsyn/component-exoscale-cloud-controller-manager/blob/master/class/defaults.yml[See `class/defaults.yml`]

The version of the Exoscale cloud-controller-manager manifests that are downloaded and rendered by the component.

The manifests are downloaded from the https://github.com/exoscale/exoscale-cloud-controller-manager[exoscale/exoscale-cloud-controller-manager] GitHub repo.

== `credentials`

[horizontal]
type:: object
default::
+
[source,yaml]
----
api_key: ?{vaultkv:${cluster:tenant}/${cluster:name}/exoscale/ccm/access_key}
api_secret: ?{vaultkv:${cluster:tenant}/${cluster:name}/exoscale/ccm/secret_key}
----

The Exoscale IAM credentials for the cloud-controller-manager.
The component will store the credentials in a secret named `exoscale-credentials` in the namespace in which the cloud-controller-manager is installed.
The component will also inject field `api-zone` with value `parameters.facts.region`.

== `nodeSelector`

[horizontal]
type:: object
default:: `{node-role.kubernetes.io/control-plane: ""}`

The node selector for the cloud-controller-manager deployment.
Change this if you don't want to run the cloud-controller-manager on your cluster's control plane nodes.
