= Deploy on existing OpenShift cluster

This guide describes how to deploy the Exoscale cloud-controller-manager (CCM) on an existing cluster.

We recommend that you migrate your cluster to use https://kb.vshn.ch/oc4/how-tos/exoscale/migrate_to_instancepool.html[instancepools for the worker nodes] before deploying the CCM.


== Prerequisites
* cluster-admin access to the cluster to migrate
* `kubectl`
* Write access to the cluster's Syn tenant repository

== Step-by-step guide

. Deploy component-exoscale-cloud-controller-manager.
Add the following to your cluster's Project Syn configuration:
+
[source,yaml]
----
applications:
  - exoscale-cloud-controller-manager
----

. Patch infrastructure config
+
IMPORTANT: This step triggers node reboots to apply the Kubelet flag `--cloud-provider=external`.
+
[source,bash]
----
kubectl --as cluster-admin patch infrastructure.config  cluster --type=merge -p '{"spec":{"platformSpec":{"external":{"platformName":"exoscale"},"type":"External"}}}'
----
+
[source,bash]
----
kubectl --as=cluster-admin patch infrastructure.config cluster --type=merge --subresource=status \
  -p  '{"status":{"platform":"External","platformStatus":{"external":{"cloudControllerManager":{"state":"External"}},"type":"External"}}}'
----

. Taint nodes with `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule`
+
[source,bash]
----
kubectl --as cluster-admin taint node --all node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
----

. Check if instance-type is applied
+
[source,bash]
----
kubectl get nodes -ocustom-columns='NAME:.metadata.name,INSTANCE_TYPE:.metadata.labels.node\.kubernetes\.io/instance-type'
----
+
[source,bash]
----
NAME                 INSTANCE_TYPE
infra-032a           standard.extra-large
infra-7b8b           standard.extra-large
infra-f8e1           standard.extra-large
infra-fa1a           standard.extra-large
master-03b1          standard.extra-large
master-4386          standard.extra-large
master-a662          standard.extra-large
storage-11b9         cpu.extra-large
storage-2764         cpu.extra-large
storage-5d24         cpu.extra-large
worker-e6e75-drjgz   standard.extra-large
worker-e6e75-ikhpr   standard.extra-large
worker-e6e75-nypky   standard.extra-large
----
